name: 'maven-build'
description: '执行 Maven 构建任务'
inputs:
  maven-command:
    description: '要执行的 Maven 命令'
    required: true
    default: 'mvn package -Dmaven.test.skip=true -U -e -X -B'
    layout:
      type: 'input'
      label: 'Maven 构建命令'

  continue-on-failure:
    description: '构建失败后是否继续执行后续任务'
    required: false
    default: 'false'
    layout:
      type: 'switch'
      label: '失败后继续运行'

runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/stop.js'


