name: 'maven-build-action'
description: '具有高级选项的自定义Maven构建管道'
author: 'WooSharing'
version: '0.0.1'
inputs:
  name:
    description: '构建任务名称'
    required: true
  maven-version:
    description: 'Maven 版本 (e.g. 3.8.6)'
    required: true
  command:
    description: 'Maven 命令 (e.g. clean install)'
    required: true
  continue-on-failure:
    description: '失败后是否继续运行'
    default: 'false'
  publish-to-repo:
    description: '发布到 CodeArts 私有依赖库'
    default: 'false'
  skip-tests:
    description: '跳过单元测试'
    default: 'false'
  enable-cache:
    description: '启用依赖包缓存'
    default: 'true'
runs:
  using: 'node20'
  main: 'src/main.js'
