name: 'pip'
author: 'wangzhou'
version: '0.0.1'
description: '这是一个流水线安装pip的插件'
inputs:
  pip-version:
    description: 'pip的版本号'
    required: true


runs:
  using: node20
  main: dist/main.js
  post: src/stop.ts

