name: 'checkout-action'
version: '0.0.1'
author: 'hjb'
description: '从CodeArts代码仓库中克隆代码，支持指定分支、tag、commitId，支持LFS、子模块、深度克隆等功能。'

inputs:
  token:
    description: 'IAM Token，用于接口鉴权'
    required: true
    default: ${{ X_AUTH_TOKEN }}
    layout:
      type: 'input'
      label: 'IAM Token'
  project_uuid:
    description: '项目 UUID（32位字符串）'
    required: true
    default: ${{ PROJECT_ID }}
    layout:
      type: 'input'
      label: '项目 ID'
  repository:
    description: '代码仓库地址'
    required: true
    layout:
      type: 'singleSelect'
      label: '选择仓库'
      extend_prop:
        api_type: 'api'
        api_options: '{
            "method": "GET",
            "url": "https://codehub.devcloud.cn-north-7.huaweicloud.com/v2/projects/${project_uuid}/repositories",
            "header": {
              "X-Auth-Token": "${token}"
            },
            "params": {
              "page_index": 1,
              "page_size": 100
            },
            "linkedFields": ["token", "project_uuid"],
            "remote": true,
            "remoteName": "search",
            "remoteQueryField": "params",
            "responseUrl": "result.repositories",
            "label": "repository_name",
            "ssh_url": "repository_uuid"
          }'
        validation:
        required_message: '请选择代码仓库'

  ref_type:
    description: '引用类型（commitId、branch、tag）'
    required: true
    default: 'branch'
    layout:
      type: 'radio'
      label: '引用类型'
      extend_prop:
        options:
          - label: 'Commit ID'
            value: 'commitId'
          - label: '分支'
            value: 'branch'
          - label: 'Tag'
            value: 'tag'
      validation:
        required_message: '请选择引用类型'

  ref_value:
    description: '引用值：分支名 / tag名 / commitId'
    required: true
    layout:
      type: 'input'
      label: '引用值'
      validation:
        required_message: '请输入引用值'

  target_path:
    description: '代码克隆的目标路径'
    required: false
    default: '.'
    layout:
      type: 'input'
      label: '目标路径'

  recurse_submodules:
    description: '是否克隆子模块'
    required: false
    default: 'false'
    layout:
      type: 'switch'
      label: '克隆子模块'

  custom_depth:
    description: '自定义克隆深度'
    required: false
    layout:
      type: 'inputNumber'
      label: '克隆深度'

  enable_lfs:
    description: '是否启用 Git LFS'
    required: false
    default: 'false'
    layout:
      type: 'switch'
      label: '启用 Git LFS'

outputs:
  checkout_status:
    description: 'Checkout执行状态'
    type: metrics
    properties:
      catalog_cn: '代码检出'
      catalog_en: 'Checkout'
      name_cn: '检出状态'
      name_en: 'Status'

runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/stop.js'
