name: 'setup-go'
version: '0.0.1'
author: 'hjb'
description: '设置 Go 环境并执行构建命令，支持多版本与架构'

inputs:
  step-name:
    description: '步骤名称'
    required: true
  go-version:
    description: 'Go版本'
    required: true
  commands:
    description: '需要执行的构建命令'
    required: true
  continue-on-error:
    description: '是否在失败后继续'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/main.js'
  post: 'dist/stop.js'
